version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: qwentes-nginx-container
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d

  php-fpm:
    build: .
    container_name: qwentes-php-container
    links:
      - mysql
    environment:
      - PHP_FPM_ENABLE=1
      - PHP_FPM_SERVER_ADDR=php
      - PHP_FPM_SERVER_PORT=9000
      - PHP_FPM_TIMEOUT=${HTTPD_TIMEOUT_TO_PHP_FPM:-180}
      - DB_HOST=mysql
      - DB_NAME=qwentes
      - DB_USER=root
      - DB_PASS=
      - DB_PORT=3306

    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql:5.7
    ports:
      - 33060:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: qwentes
      MYSQL_USER: majid
      MYSQL_PASSWORD: majid@majid
      MYSQL_ROOT_PASSWORD: root@root
    volumes:
      - my-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8888:80
    environment:
      PMA_HOST: mysql

volumes:
  my-data: